import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// ★作成したプロバイダーをインポート
import { UserProvider } from "@/hooks/useUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "2vs2 Shogi",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body className={inter.className}>
                {/* プロバイダ */}
                <UserProvider>
                    {children}
                </UserProvider>
            </body>
        </html>
    );
}
